# Generated by Django 5.2 on 2025-04-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_oncreate_entry_created_entry_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
    ]
